name: Scanner
description: Ble scanner

publish_to: 'none'

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_blue_plus: ^1.20.4
  geolocator: ^10.1.0
  permission_handler: ^11.0.1

flutter:
  uses-material-design: true
